#!/usr/bin/python -u
#
# CS3700, Spring 2015
# Project 2 Starter Code
#

import sys
import socket
import time
import datetime
import select
import json
import hashlib

def log(string):
  sys.stderr.write(datetime.datetime.now().strftime("%H:%M:%S.%f") + " " + string + "\n")


#Check if the packets checksum is the same as our current checksum
def checkSumPacket(packet):
  packetChecksum = packet['checksum']
  data = ''
  for val in packet:
    data += (str(val))
  currentChecksum = hashlib.md5(data).hexdigest()
  return packetChecksum == currentChecksum




MSG_SIZE = 1500
TIMEOUT = 30

# Bind to localhost and an ephemeral port
UDP_IP = "127.0.0.1"
#Remove as piazza post said
#UDP_PORT = 0
UDP_PORT = int(sys.argv[1])

# Set up the socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind((UDP_IP, UDP_PORT))
sock.settimeout(TIMEOUT)

# Get port we bound to
UDP_PORT = sock.getsockname()[1]
log("[bound] " + str(UDP_PORT))

# Now listen for packets
while True:
  result = sock.recvfrom(MSG_SIZE)

  # If nothing is ready, we hit the timeout
  if result:
    (data, addr) = result
    log("THIS IS THE DATA RECV: " + data)
    log("THIS IS THE ADDR RECV" + str(addr))

    try:
      decoded = json.loads(data)
      log("THIS IS DECODED DATA RECV: " + str(decoded))

      # If the EOF flag is set, exit
      if (decoded['eof']):
        log("[completed]")
        sys.exit(0)

      # If there is data, we accept it and print it out
      if (decoded['data']):
        # If we receive data, we assume it's in-order
        # You will need to do much more here
        log("[recv data] " + str(decoded['sequence']) + " (" + str(len(decoded['data'])) + ") ACCEPTED (in-order)")
        sys.stdout.write(decoded['data'])

      # Send back an ack to the sender
      msg = json.dumps({"ack": decoded['sequence'] + len(decoded['data'])})
      log("ABOUT TO SEND " + msg)
      if sock.sendto(msg, addr) < len(msg):
        log("[error] unable to fully send packet")
      else:
        log("[ACK SENT] This is the ack: " + msg)


    except (ValueError, KeyError, TypeError) as e:
      log("[recv corrupt packet] RECV SIDE")
      raise e
  else:
    log("[error] timeout RECV SIDE")
    sys.exit(-1)